# Site settings
name: Hashish Y
title: Abhishek C | Digital Design Engineer
description: Student at IIT Hyderabad, Intern at Qualcomm in SoC Integration team. 
url: https://abhi1401.github.io/
baseurl: ''
email: hashishy1701@gmail.com
cover: https://abhi1401.github.io/img/og.png
logo: https://abhi1401.github.io/img/emojis/technologist.png
resume: https://abhi1401.github.io/resume.pdf
social:
  - title: email
    url: mailto:hashishy1701@gmail.com
  - title: github
    url: https://github.com/Hashish-y
  - title: linkedin
    url: https://www.linkedin.com/in/yenugula-hashish-59162a203/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
